version: '3.4'

services:
  db:
    image: mongo:latest
    container_name: dioptra-db
    restart: always
    ports: 
      - "4005:27017"
    networks:
      - app-network

  nodejs:
    depends_on:
      - db
    build: .
    image: dioptra-frontend:latest
    container_name: dioptra-frontend
    restart: always
    env_file: .env
    environment:
      DB_CONNECTION_URI: "mongodb://dioptra-db:27017/dioptra"
      PORT: "4004"
      METRICS_ENGINE_URL: "http://metrics-engine:4006"
      DRUID_DB_URL: "http://a92314013981f428db440843327743d6-71829038.us-east-2.elb.amazonaws.com:8888/druid/v2/sql/"
      ADMIN_ORG_ID: "615e0dfeb8f78ad92061ef6f"
    ports:
      - "4004:4004"
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - ./index.mjs:/app/index.mjs
    entrypoint: /bin/sleep 36000
  metrics-engine:
    build:
      context: submodules/metrics-engine
      target: builder
    image: metrics-engine:latest
    container_name: metrics-engine
    restart: always
    environment:
      DRUID_DB_URL: "http://a92314013981f428db440843327743d6-71829038.us-east-2.elb.amazonaws.com:8888/druid/v2/sql/"
      LIMIT_EMBEDDING_QUERY: "1000"
    ports:
      - "4006:4006"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
