site_name: Dioptra
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Supported Types and Schemas: supported-types.md
  - Real-time Ingestion Api: real-time-ingestion.md
  - Batch Ingestion Api: batch-ingestion.md
  - Data Mapping: data-mapping.md
  - Segment.com: segment.md

site_dir: build/documentation

theme:
  name: "material"
  logo: logo_symbol.svg
  favicon: logo_symbol.svg
  palette:
    primary: blue grey

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
