site_name: Dioptra
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Supported types and schemas: supported_types.md
  - Real-time Ingestion api: collector.md
  - Data Mapping: data_mapping.md
  - Segment.com: segment.md

site_dir: build/documentation

theme:
  name: "material"
  logo: logo_symbol.svg
  favicon: logo_symbol.svg
  palette:
    primary: blue grey

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
