site_name: Dioptra
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Ingest data to the lake: ingestion.md
  - Download data from the lake: querying-getting-started.md
  - Metrics: metrics.md
  - Miners: miners.md
  - Tensorflow and Pytorch Utilities: tf-and-torch-utils.md
  - Active Learning: active-learning.md
  - Supported Types and Schemas: supported-types.md

site_dir: build/documentation

theme:
  name: "material"
  logo: logo_symbol.svg
  favicon: logo_symbol.svg
  palette:
    primary: blue grey

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
