apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yaml -o helm
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-{{ .Values.environment }}-mongodb
  name: {{ .Release.Name }}-{{ .Values.environment }}-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}-{{ .Values.environment }}-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yaml -o helm
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: {{ .Release.Name }}-{{ .Values.environment }}-mongodb
    spec:
      containers:
        - image: mongo:6.0.4
          name: dioptra-db
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: dioptra-dbdata
      restartPolicy: Always
      volumes:
        - name: dioptra-dbdata
          persistentVolumeClaim:
            claimName: dioptra-dbdata
status: {}
