apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: metrics-engine
  name: metrics-engine
spec:
  type: LoadBalancer
  ports:
    - name: "4006"
      port: 4006
      targetPort: 4006
  selector:
    io.kompose.service: metrics-engine
