apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-{{ .Values.environment }}-metrics-engine
  name: {{ .Release.Name }}-{{ .Values.environment }}-metrics-engine
spec:
  type: ClusterIP
  ports:
    - name: "4006"
      port: 4006
      targetPort: 4006
  selector:
    io.kompose.service: {{ .Release.Name }}-{{ .Values.environment }}-metrics-engine
