apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yaml -o helm
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-{{ .Values.environment }}-dioptra-app
  name: {{ .Release.Name }}-{{ .Values.environment }}-dioptra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}-{{ .Values.environment }}-dioptra-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yaml -o helm
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: {{ .Release.Name }}-{{ .Values.environment }}-dioptra-app
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: "{{ .Values.nodeEnv }}"
            - name: ENVIRONMENT
              value: "{{ .Values.environment }}"
            - name: COOKIE_SECRET
              value: "12345"
            - name: COOKIE_DURATION_HRS
              value: "12"
            - name: DB_CONNECTION_URI
              value: mongodb://{{ .Release.Name }}-{{ .Values.environment }}-mongodb:4005/dioptra
            - name: METRICS_ENGINE_URL
              value: http://metrics-engine:4006
            - name: DRUID_DB_URL
              value: "http://dioptra-druid-router:8888/druid/v2/sql/"
            - name: TASK_ENGINE_URL
              value: "http://task-engine:8001"
            - name: INGESTION_URL
              value: "http://ingestion:8082"
            - name: AWS_S3_CUSTOMER_BUCKET
              value: "dioptra-client-data"
            - name: AWS_S3_CUSTOMER_BUCKET_REGION
              value: "us-east-2"
            - name: PORT
              value: "4004"
            - name: PRECANNED_ORG_ID
              value: {{ .Values.precannedOrgId }}
            - name: AWS_API_GATEWAY_PLAN_ID
              value: "{{ .Values.app.awsApiGatewayPlanId }}"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-key-frontend
                  key: aws_access_key_id
                  optional: true
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-key-frontend
                  key: aws_secret_access_key
                  optional: true
          image: "641017132295.dkr.ecr.us-east-2.amazonaws.com/frontend:{{ .Values.tag }}"
          name: dioptra-frontend
          ports:
            - containerPort: 4004
          resources: {}
      restartPolicy: Always
status: {}
