apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:641017132295:certificate/619cef8b-c9dc-4313-9ab6-5bcf9a24861b
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    {{- if and .Values.app .Values.app.awsLoadBalancerSubnets }}
    service.beta.kubernetes.io/aws-load-balancer-subnets: {{ .Values.app.awsLoadBalancerSubnets }}
    {{- end }}
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-{{ .Values.environment }}-dioptra-app
  name: {{ .Release.Name }}-{{ .Values.environment }}-dioptra-app
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.app.port }}
  selector:
    io.kompose.service: {{ .Release.Name }}-{{ .Values.environment }}-dioptra-app
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-internal
  name: frontend-internal
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.app.internalPort }}}
      port: {{ .Values.app.internalPort }}}
      targetPort: {{ .Values.app.internalPort }}}
  selector:
    io.kompose.service: frontend-internal
