apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yaml -o helm
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yaml -o helm
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: nodejs
    spec:
      containers:
        - env:
            - name: DB_CONNECTION_URI
              value: mongodb://db.default.svc.cluster.local:4005/dioptra
            - name: PORT
              value: "4004"
          image: 641017132295.dkr.ecr.us-east-2.amazonaws.com/frontend:latest
          name: dioptra-frontend
          ports:
            - containerPort: 4004
          resources: {}
      restartPolicy: Always
status: {}
