apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yaml -o helm
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  type: LoadBalancer
  ports:
    - name: "4004"
      port: 4004
      targetPort: 4004
  selector:
    io.kompose.service: nodejs
status:
  loadBalancer: {}
