# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  build_test:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          # Not available in Free plan
          # docker_layer_caching: true
      - run: |
          docker build -t dioptraai/frontend .
          docker run dioptraai/frontend sh -c "npm run test"

workflows:
  # "Integration":
  #   jobs:
  #     - build_test:
  #         filters:
  #           branches:
  #             ignore:
  #               - main
  "Distribution":
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: frontend
          tag: 0.1.1.$CIRCLE_BUILD_NUM,latest
          context:
            - aws-creds
          # filters:
          #   branches:
          #     only:
          #       - main
