# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  docker: circleci/docker@1.6.0

jobs:
  build_test:
    steps:
      - checkout
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/install-docker
      - run: |
          docker run $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME sh -c "npm run test"

workflows:
  "Integration":
    jobs:
      - build_test:
          filters:
            branches:
              ignore:
                - main
  "Distribution":
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: frontend
          tag: 0.1.1.$CIRCLE_BUILD_NUM
          context:
            - aws-creds
          filters:
            branches:
              only:
                - main
