# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  helm-upgrade:
    parameters:
      cluster-name:
        type: string
      aws-region:
        type: string
        default: us-east-2
      helm-values:
        type: string
      image-tag:
        type: string
    executor: aws-eks/python
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: <<parameters.cluster-name>>
          aws-region: <<parameters.aws-region>>
      - checkout
      - helm/upgrade-helm-chart:
          atomic: true
          chart: ./helm
          helm-version: v3.6.0
          release-name: frontend
          update-repositories: false
          recreate-pods: true
          values: <<parameters.helm-values>>
          values-to-override: image=<<parameters.image-tag>>

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  node: circleci/node@4.5
  helm: circleci/helm@1.2.0
  aws-eks: circleci/aws-eks@0.2

workflows:
  "Integration":
    jobs:
      - node/test:
          name: lint
          version: 16.4.0 # This to be kept in sync with Dockerfile
          run-command: lint
      # Skipping until we have tests worth the time.
      # - node/test:
      #     name: test
      #     version: 16.4.0 # This to be kept in sync with Dockerfile
      #     requires:
      #       - lint
      - aws-ecr/build-and-push-image:
          name: build-image
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
          path: .
          region: AWS_REGION
          repo: frontend
          tag: 0.1.1.<<pipeline.number>>,latest
          context:
            - aws-creds
          requires:
            - lint
          filters:
            branches:
              only:
                - main
                - dev
      - helm-upgrade:
          name: upgrade-dev
          cluster-name: dioptra-dev-eks
          helm-values: ./helm/values.dev.yaml
          image-tag: 0.1.1.<<pipeline.number>>
          context:
            - aws-creds
          requires:
            - build-image
          filters:
            branches:
              only:
                - dev
      - helm-upgrade:
          name: upgrade-prod
          cluster-name: dioptra-prod-eks
          helm-values: ./helm/values.prod.yaml
          image-tag: 0.1.1.<<pipeline.number>>
          context:
            - aws-creds
          requires:
            - build-image
          filters:
            branches:
              only:
                - main
