# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  build_test:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          # Not available in Free plan
          # docker_layer_caching: true
      - run: |
          TAG=0.1.1.$CIRCLE_BUILD_NUM
          docker build -t dioptraai/frontend:$TAG .
          docker run dioptraai/frontend:$TAG sh -c "npm run lint && npm run test"

      - run: |
          TAG=0.1.1.$CIRCLE_BUILD_NUM
          docker build -t dioptraai/frontend:$TAG .
          docker run dioptraai/frontend:$TAG npm run test
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push dioptraai/frontend:$TAG

workflows:
  # "Integration":
  #   jobs:
  #     - build_test:
  #         filters:
  #           branches:
  #             ignore:
  #               - main
  "Distribution":
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 641017132295.dkr.ecr.us-east-2.amazonaws.com/frontend
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: circleci-ecr-orb-demo
          tag: 0.1.1.$CIRCLE_BUILD_NUM
          context:
            - aws-creds
          # filters:
          #   branches:
          #     only:
          #       - main
