# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          # Not available in Free plan
          # docker_layer_caching: true
      - run: |
          TAG=0.1.1.$CIRCLE_BUILD_NUM
          docker build -t dioptraai/frontend:$TAG .
          docker run dioptraai/frontend:$TAG -t npm run test

  build-test-push:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          # Not available in Free plan
          # docker_layer_caching: true
      - run: |
          TAG=0.1.1.$CIRCLE_BUILD_NUM
          docker build -t dioptraai/frontend:$TAG .
          docker run dioptraai/frontend:$TAG -t npm run test
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push dioptraai/frontend:$TAG

workflows:
  "Integration":
    jobs:
      - build-test
  "Distribution":
    jobs:
      - build-test-push
