environment: prod
app:
  awsLoadBalancerSubnets:
  awsLoadBalancerEipAllocations: eipalloc-00afa58958b6f54a0,eipalloc-007742ac54ac6d099
  awsApiGatewayPlanId: 'ujyzsg'
postgres:
  host: prod-postgresql-cluster.cluster-c58vxsd50oik.us-east-2.rds.amazonaws.com
  user: postgres
  secret:
    name: "dioptra-postgres"
    key: "password"
ingestionEndpoint: https://api.dioptra.ai/
awsIngestionStateMachineArn: arn:aws:states:us-east-2:641017132295:stateMachine:IngestionStateMachine-sfGkLYnxTHfT
